# Generated by Django 4.2.11 on 2026-04-24 09:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('businesses', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total amount')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Paid amount')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Remaining amount')),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], db_index=True, default='unpaid', max_length=10, verbose_name='Status')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due date')),
                ('reminder_sent', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='businesses.business', verbose_name='Business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='customers.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Debt',
                'verbose_name_plural': 'Debts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebtItem',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Snapshot of the product name at time of sale', max_length=200, verbose_name='Item name')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='debts.debt', verbose_name='Debt')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_items', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Debt Item',
                'verbose_name_plural': 'Debt Items',
            },
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['business', 'status'], name='debts_debt_busines_2bdbc6_idx'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['customer', 'status'], name='debts_debt_custome_342eab_idx'),
        ),
    ]
